"""
Visualization Engine

Generate multiple output formats: PPT, PDF, Charts, Excel
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime
import os

# For PPT generation (extend existing)
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from generators.ppt_generator import PPTGenerator

# For PDF generation
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
    from reportlab.lib.units import inch
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("⚠️  ReportLab not installed. PDF generation will be limited.")


class VisualizationEngine:
    """Generate visualizations in multiple formats"""
    
    def __init__(self, output_dir: str = "data/output"):
        """
        Initialize visualization engine
        
        Args:
            output_dir: Directory for output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_ppt(self, 
                     data: pd.DataFrame,
                     title: str = "Data Analysis",
                     charts: Optional[List[Dict]] = None) -> str:
        """
        Generate PowerPoint presentation
        
        Args:
            data: DataFrame to visualize
            title: Presentation title
            charts: List of chart configurations
            
        Returns:
            Path to generated PPT file
        """
        # Use existing PPT generator
        generator = PPTGenerator(style='professional')
        
        # Convert DataFrame to table format
        table_data = {
            'headers': data.columns.tolist(),
            'rows': data.values.tolist()[:10]  # Limit to 10 rows
        }
        
        output_path = self.output_dir / f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        
        # Generate slides
        generator.create_title_slide(title, "Generated by Smart Document Factory")
        generator.create_table_slide("Data Summary", table_data)
        
        # Add chart slides if configured
        if charts:
            for chart_config in charts:
                # This would create chart slides
                # For now, just add data slide
                pass
        
        generator.save(str(output_path))
        
        return str(output_path)
    
    def generate_pdf(self,
                     data: pd.DataFrame,
                     title: str = "Data Report",
                     include_summary: bool = True) -> str:
        """
        Generate PDF report
        
        Args:
            data: DataFrame to include
            title: Report title
            include_summary: Include data summary
            
        Returns:
            Path to generated PDF file
        """
        if not REPORTLAB_AVAILABLE:
            raise ImportError("ReportLab is required for PDF generation. Install with: pip install reportlab")
        
        output_path = self.output_dir / f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        # Create PDF
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Container for the 'Flowable' objects
        elements = []
        
        # Styles
        styles = getSampleStyleSheet()
        title_style = styles['Heading1']
        
        # Add title
        elements.append(Paragraph(title, title_style))
        elements.append(Spacer(1, 12))
        
        # Add timestamp
        timestamp = Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            styles['Normal']
        )
        elements.append(timestamp)
        elements.append(Spacer(1, 12))
        
        # Add summary if requested
        if include_summary:
            summary_text = f"""
            <b>Data Summary:</b><br/>
            - Total Rows: {len(data):,}<br/>
            - Total Columns: {len(data.columns)}<br/>
            - Columns: {', '.join(data.columns.tolist()[:10])}
            """
            elements.append(Paragraph(summary_text, styles['Normal']))
            elements.append(Spacer(1, 12))
        
        # Add data table (limited rows)
        table_data = [data.columns.tolist()] + data.head(20).values.tolist()
        
        # Create table
        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(t)
        
        # Build PDF
        doc.build(elements)
        
        return str(output_path)
    
    def generate_chart(self,
                      data: pd.DataFrame,
                      chart_type: str = 'bar',
                      x_col: Optional[str] = None,
                      y_col: Optional[str] = None,
                      title: str = "Data Visualization") -> str:
        """
        Generate interactive chart (Plotly)
        
        Args:
            data: DataFrame to visualize
            chart_type: Type of chart ('bar', 'line', 'pie', 'scatter')
            x_col: X-axis column
            y_col: Y-axis column
            title: Chart title
            
        Returns:
            Path to generated HTML file
        """
        output_path = self.output_dir / f"chart_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        # Auto-select columns if not specified
        if not x_col:
            # Use first categorical or first column
            x_col = data.columns[0]
        
        if not y_col and len(data.columns) > 1:
            # Use first numeric column
            numeric_cols = data.select_dtypes(include=['number']).columns
            y_col = numeric_cols[0] if len(numeric_cols) > 0 else data.columns[1]
        
        # Create chart based on type
        if chart_type == 'bar':
            fig = px.bar(data, x=x_col, y=y_col, title=title)
        elif chart_type == 'line':
            fig = px.line(data, x=x_col, y=y_col, title=title)
        elif chart_type == 'scatter':
            fig = px.scatter(data, x=x_col, y=y_col, title=title)
        elif chart_type == 'pie':
            fig = px.pie(data, names=x_col, values=y_col, title=title)
        else:
            # Default to bar
            fig = px.bar(data, x=x_col, y=y_col, title=title)
        
        # Update layout
        fig.update_layout(
            template='plotly_white',
            font=dict(family="Arial", size=12),
            hovermode='x unified'
        )
        
        # Save as HTML
        fig.write_html(str(output_path))
        
        return str(output_path)
    
    def generate_pivot_excel(self,
                            data: pd.DataFrame,
                            rows: List[str],
                            columns: List[str],
                            values: str,
                            aggfunc: str = 'sum',
                            title: str = "Pivot Analysis") -> str:
        """
        Generate Excel with pivot table
        
        Args:
            data: DataFrame
            rows: Pivot row dimensions
            columns: Pivot column dimensions
            values: Values to aggregate
            aggfunc: Aggregation function
            title: File title
            
        Returns:
            Path to generated Excel file
        """
        output_path = self.output_dir / f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        
        # Create pivot table
        pivot = pd.pivot_table(
            data,
            index=rows,
            columns=columns,
            values=values,
            aggfunc=aggfunc,
            fill_value=0
        )
        
        # Create Excel writer
        with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
            # Write original data
            data.to_excel(writer, sheet_name='Raw Data', index=False)
            
            # Write pivot table
            pivot.to_excel(writer, sheet_name='Pivot Table')
            
            # Write summary
            summary_data = {
                'Metric': ['Total Rows', 'Total Columns', 'Pivot Rows', 'Pivot Columns'],
                'Value': [len(data), len(data.columns), len(pivot), len(pivot.columns)]
            }
            pd.DataFrame(summary_data).to_excel(writer, sheet_name='Summary', index=False)
        
        return str(output_path)
    
    def generate_all(self,
                    data: pd.DataFrame,
                    title: str = "Analysis",
                    config: Optional[Dict] = None) -> Dict[str, str]:
        """
        Generate all output formats
        
        Args:
            data: DataFrame
            title: Title for outputs
            config: Configuration for each format
            
        Returns:
            Dict with paths to all generated files
        """
        config = config or {}
        
        results = {}
        
        try:
            results['ppt'] = self.generate_ppt(data, title)
        except Exception as e:
            results['ppt'] = f"Error: {str(e)}"
        
        try:
            results['pdf'] = self.generate_pdf(data, title)
        except Exception as e:
            results['pdf'] = f"Error: {str(e)}"
        
        try:
            results['chart'] = self.generate_chart(data, title=title)
        except Exception as e:
            results['chart'] = f"Error: {str(e)}"
        
        try:
            # Simple Excel export
            excel_path = self.output_dir / f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
            data.to_excel(excel_path, index=False)
            results['excel'] = str(excel_path)
        except Exception as e:
            results['excel'] = f"Error: {str(e)}"
        
        return results
